### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by speendo** [karunadheera/lcdpcf8574#1]
This seems to be a great project. I definitely would like to use it. Thanks for that.

Some documentation would be great though!

**Comment by retromuz** [comment]
Will add some documentation soon!

**Comment by dentex** [comment]
Yes, please tell us something:
how to run the LCD after `sudo make install` ?
What gets installed?

Thanks.

**Comment by retromuz** [comment]
Hey Dentex,

If everything went alright when you did the "make install" the library .so files get installed system_wide.
Provided you have configured your Raspberry Pi accordingly and connected circuitry as shown in the image, then you can test the LCD by running either test programs (Python / C).
Namely lcdpcf8574test.py or lcdpcf8574test.c.

Check both of them out!

Happy coding mate!

**Comment by retromuz** [comment]
Please don't hesitate to update the documentation if o have missed anything

**Comment by dentex** [comment]
Thank you very much! I figured it out afterward (I found the .py script... sorry I missed it).

All good.

Thanks, 
bye!

**Comment by retromuz** [comment]
Well, the description itself is sufficient as a documentation for this project, and as @dentex figured it out himself. Closing the issue.
